<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenEncuestaCategoria', 'doctrine');

/**
 * BaseCenEncuestaCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enc_id
 * @property string $enc_encuesta_id
 * @property integer $enc_categoria_id
 * @property integer $enc_creado_por
 * @property timestamp $enc_fecha_creacion
 * @property integer $enc_modificado_por
 * @property timestamp $enc_fecha_modificacion
 * @property integer $enc_activo
 * @property CenCategoria $CenCategoria
 * @property CenEncuesta $CenEncuesta
 * 
 * @method integer              getEncId()                  Returns the current record's "enc_id" value
 * @method string               getEncEncuestaId()          Returns the current record's "enc_encuesta_id" value
 * @method integer              getEncCategoriaId()         Returns the current record's "enc_categoria_id" value
 * @method integer              getEncCreadoPor()           Returns the current record's "enc_creado_por" value
 * @method timestamp            getEncFechaCreacion()       Returns the current record's "enc_fecha_creacion" value
 * @method integer              getEncModificadoPor()       Returns the current record's "enc_modificado_por" value
 * @method timestamp            getEncFechaModificacion()   Returns the current record's "enc_fecha_modificacion" value
 * @method integer              getEncActivo()              Returns the current record's "enc_activo" value
 * @method CenCategoria         getCenCategoria()           Returns the current record's "CenCategoria" value
 * @method CenEncuesta          getCenEncuesta()            Returns the current record's "CenEncuesta" value
 * @method CenEncuestaCategoria setEncId()                  Sets the current record's "enc_id" value
 * @method CenEncuestaCategoria setEncEncuestaId()          Sets the current record's "enc_encuesta_id" value
 * @method CenEncuestaCategoria setEncCategoriaId()         Sets the current record's "enc_categoria_id" value
 * @method CenEncuestaCategoria setEncCreadoPor()           Sets the current record's "enc_creado_por" value
 * @method CenEncuestaCategoria setEncFechaCreacion()       Sets the current record's "enc_fecha_creacion" value
 * @method CenEncuestaCategoria setEncModificadoPor()       Sets the current record's "enc_modificado_por" value
 * @method CenEncuestaCategoria setEncFechaModificacion()   Sets the current record's "enc_fecha_modificacion" value
 * @method CenEncuestaCategoria setEncActivo()              Sets the current record's "enc_activo" value
 * @method CenEncuestaCategoria setCenCategoria()           Sets the current record's "CenCategoria" value
 * @method CenEncuestaCategoria setCenEncuesta()            Sets the current record's "CenEncuesta" value
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenEncuestaCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_encuesta_categoria');
        $this->hasColumn('enc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('enc_encuesta_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enc_categoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enc_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('enc_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('enc_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CenCategoria', array(
             'local' => 'enc_categoria_id',
             'foreign' => 'cat_id'));

        $this->hasOne('CenEncuesta', array(
             'local' => 'enc_encuesta_id',
             'foreign' => 'enc_id'));
    }
}