<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenTipoEncuesta', 'doctrine');

/**
 * BaseCenTipoEncuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tpe_id
 * @property string $tpe_nombre
 * @property timestamp $tpe_fecha_creacion
 * @property integer $tpe_creado_por
 * @property timestamp $tpe_fecha_modificacion
 * @property integer $tpe_modificado_por
 * @property integer $tpe_activo
 * 
 * @method integer         getTpeId()                  Returns the current record's "tpe_id" value
 * @method string          getTpeNombre()              Returns the current record's "tpe_nombre" value
 * @method timestamp       getTpeFechaCreacion()       Returns the current record's "tpe_fecha_creacion" value
 * @method integer         getTpeCreadoPor()           Returns the current record's "tpe_creado_por" value
 * @method timestamp       getTpeFechaModificacion()   Returns the current record's "tpe_fecha_modificacion" value
 * @method integer         getTpeModificadoPor()       Returns the current record's "tpe_modificado_por" value
 * @method integer         getTpeActivo()              Returns the current record's "tpe_activo" value
 * @method CenTipoEncuesta setTpeId()                  Sets the current record's "tpe_id" value
 * @method CenTipoEncuesta setTpeNombre()              Sets the current record's "tpe_nombre" value
 * @method CenTipoEncuesta setTpeFechaCreacion()       Sets the current record's "tpe_fecha_creacion" value
 * @method CenTipoEncuesta setTpeCreadoPor()           Sets the current record's "tpe_creado_por" value
 * @method CenTipoEncuesta setTpeFechaModificacion()   Sets the current record's "tpe_fecha_modificacion" value
 * @method CenTipoEncuesta setTpeModificadoPor()       Sets the current record's "tpe_modificado_por" value
 * @method CenTipoEncuesta setTpeActivo()              Sets the current record's "tpe_activo" value
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenTipoEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_tipo_encuesta');
        $this->hasColumn('tpe_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('tpe_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('tpe_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tpe_creado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tpe_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tpe_modificado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tpe_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}