<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenEncuestaMaster', 'doctrine');

/**
 * BaseCenEncuestaMaster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $encm_id
 * @property string $encm_encuesta_id
 * @property integer $encm_creado_por
 * @property timestamp $encm_fecha_creacion
 * @property integer $encm_modificado_por
 * @property timestamp $encm_fecha_modificacion
 * @property integer $encm_activo
 * 
 * @method integer           getEncmId()                  Returns the current record's "encm_id" value
 * @method string            getEncmEncuestaId()          Returns the current record's "encm_encuesta_id" value
 * @method integer           getEncmCreadoPor()           Returns the current record's "encm_creado_por" value
 * @method timestamp         getEncmFechaCreacion()       Returns the current record's "encm_fecha_creacion" value
 * @method integer           getEncmModificadoPor()       Returns the current record's "encm_modificado_por" value
 * @method timestamp         getEncmFechaModificacion()   Returns the current record's "encm_fecha_modificacion" value
 * @method integer           getEncmActivo()              Returns the current record's "encm_activo" value
 * @method CenEncuestaMaster setEncmId()                  Sets the current record's "encm_id" value
 * @method CenEncuestaMaster setEncmEncuestaId()          Sets the current record's "encm_encuesta_id" value
 * @method CenEncuestaMaster setEncmCreadoPor()           Sets the current record's "encm_creado_por" value
 * @method CenEncuestaMaster setEncmFechaCreacion()       Sets the current record's "encm_fecha_creacion" value
 * @method CenEncuestaMaster setEncmModificadoPor()       Sets the current record's "encm_modificado_por" value
 * @method CenEncuestaMaster setEncmFechaModificacion()   Sets the current record's "encm_fecha_modificacion" value
 * @method CenEncuestaMaster setEncmActivo()              Sets the current record's "encm_activo" value
 * @property  $
 * @property SfGuardUser $
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenEncuestaMaster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_encuesta_master');
        $this->hasColumn('encm_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('encm_encuesta_id', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('encm_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('encm_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('encm_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('encm_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('encm_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SfGuardUser', array(
             'local' => 'encm_creado_por',
             'foreign' => 'id'));

        $this->hasMany('SfGuardUser', array(
             'local' => 'encm_modificado_por',
             'foreign' => 'id'));
    }
}