<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenCategoria', 'doctrine');

/**
 * BaseCenCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cat_id
 * @property string $cat_nombre
 * @property integer $cat_es_datos_clasificacion
 * @property integer $cat_creado_por
 * @property timestamp $cat_fecha_creacion
 * @property integer $cat_modificado_por
 * @property timestamp $cat_fecha_modificacion
 * @property integer $cat_activo
 * @property Doctrine_Collection $CenEncuestaCategoria
 * 
 * @method integer             getCatId()                      Returns the current record's "cat_id" value
 * @method string              getCatNombre()                  Returns the current record's "cat_nombre" value
 * @method integer             getCatEsDatosClasificacion()    Returns the current record's "cat_es_datos_clasificacion" value
 * @method integer             getCatCreadoPor()               Returns the current record's "cat_creado_por" value
 * @method timestamp           getCatFechaCreacion()           Returns the current record's "cat_fecha_creacion" value
 * @method integer             getCatModificadoPor()           Returns the current record's "cat_modificado_por" value
 * @method timestamp           getCatFechaModificacion()       Returns the current record's "cat_fecha_modificacion" value
 * @method integer             getCatActivo()                  Returns the current record's "cat_activo" value
 * @method Doctrine_Collection getCenEncuestaCategoria()       Returns the current record's "CenEncuestaCategoria" collection
 * @method CenCategoria        setCatId()                      Sets the current record's "cat_id" value
 * @method CenCategoria        setCatNombre()                  Sets the current record's "cat_nombre" value
 * @method CenCategoria        setCatEsDatosClasificacion()    Sets the current record's "cat_es_datos_clasificacion" value
 * @method CenCategoria        setCatCreadoPor()               Sets the current record's "cat_creado_por" value
 * @method CenCategoria        setCatFechaCreacion()           Sets the current record's "cat_fecha_creacion" value
 * @method CenCategoria        setCatModificadoPor()           Sets the current record's "cat_modificado_por" value
 * @method CenCategoria        setCatFechaModificacion()       Sets the current record's "cat_fecha_modificacion" value
 * @method CenCategoria        setCatActivo()                  Sets the current record's "cat_activo" value
 * @method CenCategoria        setCenEncuestaCategoria()       Sets the current record's "CenEncuestaCategoria" collection
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_categoria');
        $this->hasColumn('cat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cat_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('cat_es_datos_clasificacion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('cat_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cat_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cat_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('cat_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('cat_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CenEncuestaCategoria', array(
             'local' => 'cat_id',
             'foreign' => 'enc_categoria_id'));
    }
}