<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenEncuestas', 'doctrine');

/**
 * BaseCenEncuestas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enc_id
 * @property string $enc_nombre
 * @property string $enc_descripcion
 * @property timestamp $enc_fecha_creacion
 * @property integer $enc_creado_por
 * @property timestamp $enc_fecha_modificacion
 * @property integer $enc_modificado_por
 * @property integer $enc_activo
 * @property Doctrine_Collection $CenPregunta
 * 
 * @method integer             getEncId()                  Returns the current record's "enc_id" value
 * @method string              getEncNombre()              Returns the current record's "enc_nombre" value
 * @method string              getEncDescripcion()         Returns the current record's "enc_descripcion" value
 * @method timestamp           getEncFechaCreacion()       Returns the current record's "enc_fecha_creacion" value
 * @method integer             getEncCreadoPor()           Returns the current record's "enc_creado_por" value
 * @method timestamp           getEncFechaModificacion()   Returns the current record's "enc_fecha_modificacion" value
 * @method integer             getEncModificadoPor()       Returns the current record's "enc_modificado_por" value
 * @method integer             getEncActivo()              Returns the current record's "enc_activo" value
 * @method Doctrine_Collection getCenPregunta()            Returns the current record's "CenPregunta" collection
 * @method CenEncuestas        setEncId()                  Sets the current record's "enc_id" value
 * @method CenEncuestas        setEncNombre()              Sets the current record's "enc_nombre" value
 * @method CenEncuestas        setEncDescripcion()         Sets the current record's "enc_descripcion" value
 * @method CenEncuestas        setEncFechaCreacion()       Sets the current record's "enc_fecha_creacion" value
 * @method CenEncuestas        setEncCreadoPor()           Sets the current record's "enc_creado_por" value
 * @method CenEncuestas        setEncFechaModificacion()   Sets the current record's "enc_fecha_modificacion" value
 * @method CenEncuestas        setEncModificadoPor()       Sets the current record's "enc_modificado_por" value
 * @method CenEncuestas        setEncActivo()              Sets the current record's "enc_activo" value
 * @method CenEncuestas        setCenPregunta()            Sets the current record's "CenPregunta" collection
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenEncuestas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_encuestas');
        $this->hasColumn('enc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('enc_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enc_descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('enc_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_creado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enc_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_modificado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enc_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CenPregunta', array(
             'local' => 'enc_id',
             'foreign' => 'pre_id_encuesta'));
    }
}