<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenPregunta', 'doctrine');

/**
 * BaseCenPregunta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pre_id
 * @property integer $pre_id_encuesta
 * @property integer $pre_id_tipo_pregunta_opcion
 * @property string $pre_pregunta_text
 * @property integer $pre_posicion
 * @property integer $pre_padre
 * @property string $pre_nota
 * @property string $pre_descripcion
 * @property timestamp $pre_fecha_creacion
 * @property integer $pre_creado_por
 * @property timestamp $pre_fecha_modificacion
 * @property integer $pre_modificado_por
 * @property integer $pre_activo
 * @property CenTipoPreguntaOpcion $CenTipoPreguntaOpcion
 * @property Doctrine_Collection $CenOpcion
 * @property CenEncuestas $CenEncuestas
 * 
 * @method integer               getPreId()                       Returns the current record's "pre_id" value
 * @method integer               getPreIdEncuesta()               Returns the current record's "pre_id_encuesta" value
 * @method integer               getPreIdTipoPreguntaOpcion()     Returns the current record's "pre_id_tipo_pregunta_opcion" value
 * @method string                getPrePreguntaText()             Returns the current record's "pre_pregunta_text" value
 * @method integer               getPrePosicion()                 Returns the current record's "pre_posicion" value
 * @method integer               getPrePadre()                    Returns the current record's "pre_padre" value
 * @method string                getPreNota()                     Returns the current record's "pre_nota" value
 * @method string                getPreDescripcion()              Returns the current record's "pre_descripcion" value
 * @method timestamp             getPreFechaCreacion()            Returns the current record's "pre_fecha_creacion" value
 * @method integer               getPreCreadoPor()                Returns the current record's "pre_creado_por" value
 * @method timestamp             getPreFechaModificacion()        Returns the current record's "pre_fecha_modificacion" value
 * @method integer               getPreModificadoPor()            Returns the current record's "pre_modificado_por" value
 * @method integer               getPreActivo()                   Returns the current record's "pre_activo" value
 * @method CenTipoPreguntaOpcion getCenTipoPreguntaOpcion()       Returns the current record's "CenTipoPreguntaOpcion" value
 * @method Doctrine_Collection   getCenOpcion()                   Returns the current record's "CenOpcion" collection
 * @method CenEncuestas          getCenEncuestas()                Returns the current record's "CenEncuestas" value
 * @method CenPregunta           setPreId()                       Sets the current record's "pre_id" value
 * @method CenPregunta           setPreIdEncuesta()               Sets the current record's "pre_id_encuesta" value
 * @method CenPregunta           setPreIdTipoPreguntaOpcion()     Sets the current record's "pre_id_tipo_pregunta_opcion" value
 * @method CenPregunta           setPrePreguntaText()             Sets the current record's "pre_pregunta_text" value
 * @method CenPregunta           setPrePosicion()                 Sets the current record's "pre_posicion" value
 * @method CenPregunta           setPrePadre()                    Sets the current record's "pre_padre" value
 * @method CenPregunta           setPreNota()                     Sets the current record's "pre_nota" value
 * @method CenPregunta           setPreDescripcion()              Sets the current record's "pre_descripcion" value
 * @method CenPregunta           setPreFechaCreacion()            Sets the current record's "pre_fecha_creacion" value
 * @method CenPregunta           setPreCreadoPor()                Sets the current record's "pre_creado_por" value
 * @method CenPregunta           setPreFechaModificacion()        Sets the current record's "pre_fecha_modificacion" value
 * @method CenPregunta           setPreModificadoPor()            Sets the current record's "pre_modificado_por" value
 * @method CenPregunta           setPreActivo()                   Sets the current record's "pre_activo" value
 * @method CenPregunta           setCenTipoPreguntaOpcion()       Sets the current record's "CenTipoPreguntaOpcion" value
 * @method CenPregunta           setCenOpcion()                   Sets the current record's "CenOpcion" collection
 * @method CenPregunta           setCenEncuestas()                Sets the current record's "CenEncuestas" value
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenPregunta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_pregunta');
        $this->hasColumn('pre_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pre_id_encuesta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_id_tipo_pregunta_opcion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_pregunta_text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pre_posicion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_padre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_nota', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pre_descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pre_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pre_creado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pre_modificado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pre_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CenTipoPreguntaOpcion', array(
             'local' => 'pre_id_tipo_pregunta_opcion',
             'foreign' => 'tpo_id'));

        $this->hasMany('CenOpcion', array(
             'local' => 'pre_id',
             'foreign' => 'opc_id_pregunta'));

        $this->hasOne('CenEncuestas', array(
             'local' => 'pre_id_encuesta',
             'foreign' => 'enc_id'));
    }
}