<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenPais', 'doctrine');

/**
 * BaseCenPais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pai_id
 * @property string $pai_nombre
 * @property timestamp $pai_fecha_creacion
 * @property integer $pai_creado_por
 * @property timestamp $pai_fecha_modificacion
 * @property integer $pai_modificado_por
 * @property integer $pai_activo
 * @property Doctrine_Collection $CenEncuesta
 * 
 * @method integer             getPaiId()                  Returns the current record's "pai_id" value
 * @method string              getPaiNombre()              Returns the current record's "pai_nombre" value
 * @method timestamp           getPaiFechaCreacion()       Returns the current record's "pai_fecha_creacion" value
 * @method integer             getPaiCreadoPor()           Returns the current record's "pai_creado_por" value
 * @method timestamp           getPaiFechaModificacion()   Returns the current record's "pai_fecha_modificacion" value
 * @method integer             getPaiModificadoPor()       Returns the current record's "pai_modificado_por" value
 * @method integer             getPaiActivo()              Returns the current record's "pai_activo" value
 * @method Doctrine_Collection getCenEncuesta()            Returns the current record's "CenEncuesta" collection
 * @method CenPais             setPaiId()                  Sets the current record's "pai_id" value
 * @method CenPais             setPaiNombre()              Sets the current record's "pai_nombre" value
 * @method CenPais             setPaiFechaCreacion()       Sets the current record's "pai_fecha_creacion" value
 * @method CenPais             setPaiCreadoPor()           Sets the current record's "pai_creado_por" value
 * @method CenPais             setPaiFechaModificacion()   Sets the current record's "pai_fecha_modificacion" value
 * @method CenPais             setPaiModificadoPor()       Sets the current record's "pai_modificado_por" value
 * @method CenPais             setPaiActivo()              Sets the current record's "pai_activo" value
 * @method CenPais             setCenEncuesta()            Sets the current record's "CenEncuesta" collection
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenPais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_pais');
        $this->hasColumn('pai_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pai_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('pai_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pai_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pai_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('pai_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('pai_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CenEncuesta', array(
             'local' => 'pai_id',
             'foreign' => 'enc_pais'));
    }
}