<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenOpcion', 'doctrine');

/**
 * BaseCenOpcion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $opc_id
 * @property integer $opc_id_pregunta
 * @property string $opc_opcion
 * @property integer $opc_creador_por
 * @property timestamp $opc_fecha_creacion
 * @property integer $opc_modificado_por
 * @property integer $opc_activo
 * @property CenPregunta $CenPregunta
 * 
 * @method integer     getOpcId()              Returns the current record's "opc_id" value
 * @method integer     getOpcIdPregunta()      Returns the current record's "opc_id_pregunta" value
 * @method string      getOpcOpcion()          Returns the current record's "opc_opcion" value
 * @method integer     getOpcCreadorPor()      Returns the current record's "opc_creador_por" value
 * @method timestamp   getOpcFechaCreacion()   Returns the current record's "opc_fecha_creacion" value
 * @method integer     getOpcModificadoPor()   Returns the current record's "opc_modificado_por" value
 * @method integer     getOpcActivo()          Returns the current record's "opc_activo" value
 * @method CenPregunta getCenPregunta()        Returns the current record's "CenPregunta" value
 * @method CenOpcion   setOpcId()              Sets the current record's "opc_id" value
 * @method CenOpcion   setOpcIdPregunta()      Sets the current record's "opc_id_pregunta" value
 * @method CenOpcion   setOpcOpcion()          Sets the current record's "opc_opcion" value
 * @method CenOpcion   setOpcCreadorPor()      Sets the current record's "opc_creador_por" value
 * @method CenOpcion   setOpcFechaCreacion()   Sets the current record's "opc_fecha_creacion" value
 * @method CenOpcion   setOpcModificadoPor()   Sets the current record's "opc_modificado_por" value
 * @method CenOpcion   setOpcActivo()          Sets the current record's "opc_activo" value
 * @method CenOpcion   setCenPregunta()        Sets the current record's "CenPregunta" value
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenOpcion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_opcion');
        $this->hasColumn('opc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('opc_id_pregunta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('opc_opcion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('opc_creador_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('opc_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('opc_modificado_por', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('opc_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CenPregunta', array(
             'local' => 'opc_id_pregunta',
             'foreign' => 'pre_id'));
    }
}