<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenUsuarioConfiguracion', 'doctrine');

/**
 * BaseCenUsuarioConfiguracion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usc_id
 * @property integer $usc_user_id
 * @property integer $usc_guider
 * @property integer $usc_creado_por
 * @property timestamp $usc_fecha_creacion
 * @property integer $usc_modificado_por
 * @property timestamp $usc_fecha_modificacion
 * @property integer $usc_activo
 * 
 * @method integer                 getUscId()                  Returns the current record's "usc_id" value
 * @method integer                 getUscUserId()              Returns the current record's "usc_user_id" value
 * @method integer                 getUscGuider()              Returns the current record's "usc_guider" value
 * @method integer                 getUscCreadoPor()           Returns the current record's "usc_creado_por" value
 * @method timestamp               getUscFechaCreacion()       Returns the current record's "usc_fecha_creacion" value
 * @method integer                 getUscModificadoPor()       Returns the current record's "usc_modificado_por" value
 * @method timestamp               getUscFechaModificacion()   Returns the current record's "usc_fecha_modificacion" value
 * @method integer                 getUscActivo()              Returns the current record's "usc_activo" value
 * @method CenUsuarioConfiguracion setUscId()                  Sets the current record's "usc_id" value
 * @method CenUsuarioConfiguracion setUscUserId()              Sets the current record's "usc_user_id" value
 * @method CenUsuarioConfiguracion setUscGuider()              Sets the current record's "usc_guider" value
 * @method CenUsuarioConfiguracion setUscCreadoPor()           Sets the current record's "usc_creado_por" value
 * @method CenUsuarioConfiguracion setUscFechaCreacion()       Sets the current record's "usc_fecha_creacion" value
 * @method CenUsuarioConfiguracion setUscModificadoPor()       Sets the current record's "usc_modificado_por" value
 * @method CenUsuarioConfiguracion setUscFechaModificacion()   Sets the current record's "usc_fecha_modificacion" value
 * @method CenUsuarioConfiguracion setUscActivo()              Sets the current record's "usc_activo" value
 * @property  $
 * @property SfGuardUser $
 * @property SfGuardUser $
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenUsuarioConfiguracion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_usuario_configuracion');
        $this->hasColumn('usc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usc_user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('usc_guider', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('usc_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('usc_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('usc_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('usc_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('usc_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SfGuardUser', array(
             'local' => 'usc_creado_por',
             'foreign' => 'id'));

        $this->hasMany('SfGuardUser', array(
             'local' => 'usc_modificado_por',
             'foreign' => 'id'));

        $this->hasMany('SfGuardUser', array(
             'local' => 'usc_user_id',
             'foreign' => 'id'));
    }
}