<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CenEncuesta', 'doctrine');

/**
 * BaseCenEncuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enc_id
 * @property string $enc_nombre
 * @property string $enc_instruccion
 * @property string $enc_bem
 * @property integer $enc_pais
 * @property string $enc_clave
 * @property timestamp $enc_fecha_creacion
 * @property integer $enc_creado_por
 * @property timestamp $enc_fecha_modificacion
 * @property integer $enc_modificado_por
 * @property integer $enc_activo
 * @property CenPais $CenPais
 * 
 * @method integer     getEncId()                  Returns the current record's "enc_id" value
 * @method string      getEncNombre()              Returns the current record's "enc_nombre" value
 * @method string      getEncInstruccion()         Returns the current record's "enc_instruccion" value
 * @method string      getEncBem()                 Returns the current record's "enc_bem" value
 * @method integer     getEncPais()                Returns the current record's "enc_pais" value
 * @method string      getEncClave()               Returns the current record's "enc_clave" value
 * @method timestamp   getEncFechaCreacion()       Returns the current record's "enc_fecha_creacion" value
 * @method integer     getEncCreadoPor()           Returns the current record's "enc_creado_por" value
 * @method timestamp   getEncFechaModificacion()   Returns the current record's "enc_fecha_modificacion" value
 * @method integer     getEncModificadoPor()       Returns the current record's "enc_modificado_por" value
 * @method integer     getEncActivo()              Returns the current record's "enc_activo" value
 * @method CenPais     getCenPais()                Returns the current record's "CenPais" value
 * @method CenEncuesta setEncId()                  Sets the current record's "enc_id" value
 * @method CenEncuesta setEncNombre()              Sets the current record's "enc_nombre" value
 * @method CenEncuesta setEncInstruccion()         Sets the current record's "enc_instruccion" value
 * @method CenEncuesta setEncBem()                 Sets the current record's "enc_bem" value
 * @method CenEncuesta setEncPais()                Sets the current record's "enc_pais" value
 * @method CenEncuesta setEncClave()               Sets the current record's "enc_clave" value
 * @method CenEncuesta setEncFechaCreacion()       Sets the current record's "enc_fecha_creacion" value
 * @method CenEncuesta setEncCreadoPor()           Sets the current record's "enc_creado_por" value
 * @method CenEncuesta setEncFechaModificacion()   Sets the current record's "enc_fecha_modificacion" value
 * @method CenEncuesta setEncModificadoPor()       Sets the current record's "enc_modificado_por" value
 * @method CenEncuesta setEncActivo()              Sets the current record's "enc_activo" value
 * @method CenEncuesta setCenPais()                Sets the current record's "CenPais" value
 * 
 * @package    generador_encuestas
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCenEncuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cen_encuesta');
        $this->hasColumn('enc_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enc_nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enc_instruccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('enc_bem', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enc_pais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enc_clave', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('enc_fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_creado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('enc_fecha_modificacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('enc_modificado_por', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('enc_activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CenPais', array(
             'local' => 'enc_pais',
             'foreign' => 'pai_id'));
    }
}