<?php

/**
 * CenCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenCategoria');
    }
	
	/*
	 * return all the categories
	 * @param $iHydratationMode integer
	 */
	public function getAllCategories($iHydratationMode = null) {
		return $this->findAll($iHydratationMode);
	}
	
	/*
	 * 
	 */
	public function getAllActiveCategories($iHydratationMode = null) {
		$return = $this->findBy("cat_activo", 1, $iHydratationMode);
		return $return;
	}
}