<?php

/**
 * CenCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenCategoria');
    }
}