<?php

/**
 * CenEncuestaCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenEncuestaCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenEncuestaCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenEncuestaCategoria');
    }
}