<?php

/**
 * CenEncuestasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenEncuestasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenEncuestasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenEncuestas');
    }
}