<?php

/**
 * CenEncuestaMasterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenEncuestaMasterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenEncuestaMasterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenEncuestaMaster');
    }
}