<?php

/**
 * CenEncuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenEncuestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenEncuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenEncuesta');
    }
}