<?php

/**
 * CenOpcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenOpcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenOpcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenOpcion');
    }
}