<?php

/**
 * CenPaisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenPaisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenPaisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenPais');
    }
}