<?php

/**
 * CenPreguntaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenPreguntaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenPreguntaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenPregunta');
    }
}