<?php

/**
 * CenTipoEncuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenTipoEncuestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenTipoEncuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenTipoEncuesta');
    }
}