<?php

/**
 * CenTipoPreguntaOpcionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenTipoPreguntaOpcionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenTipoPreguntaOpcionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenTipoPreguntaOpcion');
    }
}