<?php

/**
 * CenUsuarioConfiguracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenUsuarioConfiguracionTable extends Doctrine_Table {

	/**
	 * Returns an instance of this class.
	 *
	 * @return object CenUsuarioConfiguracionTable
	 */
	public static function getInstance() {
		return Doctrine_Core::getTable('CenUsuarioConfiguracion');
	}

	public function setUserConf($iUserId, $iUserOwner, $aConfOptions) {
		try {
			if ($this->checkExistenceUserConf($iUserId)) {
				$oCenUsuarioConfiguracion = new CenUsuarioConfiguracion();
				$oCenUsuarioConfiguracion->setUscCreadoPor($iUserOwner);
				$oCenUsuarioConfiguracion->setUscFechaCreacion(date("Y-m-d h:i:s"));
			} else {
				$oCenUsuarioConfiguracion = $this->findOneBy("usc_user_id", $iUserId);
			}
			$oCenUsuarioConfiguracion->setUscActivo($aConfOptions["usc_activo"]);
			$oCenUsuarioConfiguracion->setUscFechaModificacion(date("Y-m-d h:i:s"));
			$oCenUsuarioConfiguracion->setUscGuider($aConfOptions["usc_guider"]);
			$oCenUsuarioConfiguracion->setUscUserId($iUserId);
			$oCenUsuarioConfiguracion->setUscModificadoPor($iUserOwner);
			$oCenUsuarioConfiguracion->save();
		} catch (Exception $exc) {
			throw new Exception("Usuario no configurado correctamente debido a: " . $exc->getCode() . "::" . $exc->getMessage());
		}
	}

	private function checkExistenceUserConf($iUserId) {
		try {
			$aUserConfiguration = Doctrine_Core::getTable("CenUsuarioConfiguracion")->findOneBy("usc_user_id", $iUserId, Doctrine_Core::HYDRATE_ARRAY);
			$bChecked = empty($aUserConfiguration);
		} catch (Exception $exc) {
			echo $exc->getTraceAsString();
		}
		return $bChecked;
	}

}