<?php

/**
 * CenUsuarioConfiguracionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenUsuarioConfiguracionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenUsuarioConfiguracionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CenUsuarioConfiguracion');
    }
}