# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_guard_plugin:
    remember_key_expiration_age: 86400
    remember_cookie_name: generador_encuestas_frontend_RememberMe
    routes_register: false
    success_signin_url:        encuesta/index
    session_name: generadorEncuestasFrontendSession
