<?php

/**
 * sfGuardGroupPermissionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupPermissionTable extends PluginsfGuardGroupPermissionTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardGroupPermissionTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardGroupPermission');
	}

	/*
 	* This function will delete all the permission so the new permission can be added in the action
 	* @sUserId = string
 	*/

	public function doDeactiveSfGuardPermissionByGroupId($sGroupId) {
    	$dql = $this->createQuery("g")
            	->delete()
            	->where("g.group_id = ?", $sGroupId);
    	$dql->execute();
	}

	/*
 	* This function will delete all the permission so the new permission can be added in the action
 	* @sUserId = string
 	*/

	public function doDeactiveSfGuardGroupByPermissionId($sPermissionId) {
    	$dql = $this->createQuery("g")
            	->delete()
            	->where("g.permission_id = ?", $sPermissionId);
    	$dql->execute();
	}

}

