<?php

/**
 * sfGuardPermissionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardPermissionTable extends PluginsfGuardPermissionTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardPermissionTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardPermission');
	}

	/*
 	*
 	*/

	public function getActiveSfGuardPermissionByUserId($sUserId, $iHydratationMethod) {
    	$dql = $this->createQuery("p")
            	->innerJoin("p.sfGuardUserPermission up")
            	->where("up.user_id = {$sUserId}")
            	->groupBy("p.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardPermission = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardPermission->toArray();
    	} else {
        	$return = $aSfGuardPermission;
    	}
    	return $return;
	}
	/*
 	*
 	*/

	public function getActiveSfGuardPermissionByGroupId($sGroupId, $iHydratationMethod) {
    	$dql = $this->createQuery("p")
            	->innerJoin("p.sfGuardGroupPermission gp")
            	->where("gp.group_id = {$sGroupId}")
            	->groupBy("p.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardPermission = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardPermission->toArray();
    	} else {
        	$return = $aSfGuardPermission;
    	}
    	return $return;
	}

}