<?php

/**
 * sfGuardUserTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardUserTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardUser');
	}

	/*
 	*
 	*/

	public function getActiveSfGuardUserByPermissionId($sPermissionId, $iHydratationMethod) {
    	$dql = $this->createQuery("u")
            	->innerJoin("u.sfGuardUserPermission up")
            	->where("up.permission_id = {$sPermissionId}")
            	->groupBy("u.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardUser = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardUser->toArray();
    	} else {
        	$return = $aSfGuardUser;
    	}
    	return $return;
	}

}