<?php

/**
 * sfGuardUserPermissionTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserPermissionTable extends PluginsfGuardUserPermissionTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardUserPermissionTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardUserPermission');
	}

	/*
 	* This function will delete all the permission so the new permission can be added in the action
 	* @sUserId = string
 	*/

	public function doDeactiveSfGuardPermissionByUserId($sUserId) {
    	$dql = $this->createQuery("p")
            	->delete()
            	->where("p.user_id = ?", $sUserId);
    	$dql->execute();
	}

	/*
 	* This function will delete all the permission so the new permission can be added in the action
 	* @sUserId = string
 	*/

	public function doDeactiveSfGuardPermissionByPermissionId($sPermissionId) {
    	$dql = $this->createQuery("p")
            	->delete()
            	->where("p.permission_id = ?", $sPermissionId);
    	$dql->execute();
	}

}