<?php

/**
 * sfGuardUserGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserGroupTable extends PluginsfGuardUserGroupTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardUserGroupTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardUserGroup');
	}

	/*
 	* This function will delete all the group so the new permission can be added in the action
 	* @sUserId = string
 	*/

	public function doDeactiveSfGuardGroupByUserId($sUserId) {
    	$dql = $this->createQuery("g")
            	->delete()
            	->where("g.user_id = ?", $sUserId);
    	$dql->execute();
	}
    
	public function doDeactiveSfGuardUserByGroupId($sGroupId) {
    	$dql = $this->createQuery("u")
            	->delete()
            	->where("u.group_id = ?", $sGroupId);
    	$dql->execute();
	}
}