<?php

/**
 * sfGuardGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardGroupTable extends PluginsfGuardGroupTable {

	/**
 	* Returns an instance of this class.
 	*
 	* @return object sfGuardGroupTable
 	*/
	public static function getInstance() {
    	return Doctrine_Core::getTable('sfGuardGroup');
	}

	/*
 	*
 	*/

	public function getActiveSfGuardGroupByUserId($sUserId, $iHydratationMethod) {
    	$dql = $this->createQuery("g")
            	->innerJoin("g.sfGuardUserGroup ug")
            	->where("ug.user_id = {$sUserId}")
            	->groupBy("g.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardGroup = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardGroup->toArray();
    	} else {
        	$return = $aSfGuardGroup;
    	}
    	return $return;
	}

	public function getActiveSfGuardUserByGroupId($sGroupId, $iHydratationMethod) {
    	$dql = $this->createQuery("u")
            	->innerJoin("u.sfGuardUserGroup ug")
            	->where("ug.group_id = {$sGroupId}")
            	->groupBy("u.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardGroup = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardGroup->toArray();
    	} else {
        	$return = $aSfGuardGroup;
    	}
    	return $return;
	}

	public function getActiveSfGuardGroupByPermissionId($sPermissionId, $iHydratationMethod) {
    	$dql = $this->createQuery("g")
            	->innerJoin("g.sfGuardGroupPermission gp")
            	->where("gp.permission_id = {$sPermissionId}")
            	->groupBy("g.id");
    	$query = $dql->getSqlQuery();
    	$aSfGuardPermission = $dql->execute();
    	if ($iHydratationMethod == Doctrine_Core::HYDRATE_ARRAY) {
        	$return = $aSfGuardPermission->toArray();
    	} else {
        	$return = $aSfGuardPermission;
    	}
    	return $return;
	}

}

